version: "3"
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_HOST: db
    ports:
      - "3406:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
  app:
    build: .
    ports:
      - "3001:3000"
    env_file: ./.env
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    depends_on:
      - db
